### PR TITLE
Update Tween to include more parameters

### PR DESCRIPTION
**Pull request by Magnogen**
`ease` (expects a fuction that returns a value, or a fuction that returns a function that returns a value)
- Specifies the type of easing to use, built in ease types include `Tween.EASE_IN_SINE`, `Tween.EASE_OUT_CIRCULAR`, or even `Tween.EASE_IN_OUT_POWER`
- In the case of `Tween.EASE_..._POWER` and `Tween.EASE_..._EXPONENTIAL` (or just `Tween.EASE_..._EXP`), you can specify a strength parameter as if it were a function; `Tween.EASE_..._POWER(3)` would be the same as Cubic Tweening, _or_ you can use the `strength` parameter, it works exactly the same.

I plan on adding support for number of bounces in `Tween.EASE_..._BOUNCE`, as well as dampening for `Tween.EASE_..._ELASTIC`, but idk how to do that yet lol

### CODE REVIEW

**Comment by Magnogen** [comment]
Aight now the `EASE_..._EXPONENTIAL(strength)` works a lot nicer, here's a comparison:

ezgif-3-1ff566c6f5

It's very similar to `EASE_..._POWER(strength)`, just slightly different

Comparison:
ezgif-3-a7859f4788

**Comment by l2wilson94** [comment]
This is looking really cool!

I'll have a closer look at it when I'm at my computer!

**Comment by Magnogen** [comment]
The main difference between `EXP(strength)` and `POWER(strength)` is that `EXP` forms a straight line when the strength is 0, whereas `POWER` forms a straight line at 1 - as shown (green is `EXPONENTIAL`, blue is `POWER`)

ezgif-3-256dea3e11

**Comment by l2wilson94** [comment]
Still haven't forgotten about this! Hopefully I can merge today or tomorrow!

**Pull request merged**
